name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: REMOVE ME
      run: which go && echo $PATH

    - name: Install Go linter
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/bin v1.22.2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make

    - name: Lint
      run: make lint

    - name: Test
      run: make test
